app/controller/site/__init__.py
from flask import Blueprint

from config import TEMPLATES_DIR, STATIC_DIR

# 创建一个蓝图对象，设置别名，模板文件地址，静态文件地址
site = Blueprint('site', __name__,
    template_folder=TEMPLATES_DIR,
    static_folder=STATIC_DIR)

# 这里导入是为了在解释时，蓝图能加载到views文件中的路由数据
from app.controller.site import views

app/controller/site/views.py
from flask import (
    render_template, 
    redirect, 
    jsonify, 
    request, 
    flash, 
    url_for, 
    get_flashed_messages, 
    abort
)
from flask_login import (
    login_user, 
    logout_user, 
    login_required, 
    current_user
)
from flask_principal import (
    identity_changed, 
    current_app, 
    Identity,
    AnonymousIdentity, 
    Permission, 
    UserNeed
)
from app.plugins import (
    db, 
    permission_poster, 
    permission_admin, 
    cache
)
from app.database.models import BlogUser
# 导入表单验证
from app.forms.auth import *


# 获取蓝图
from app.controller.site import site

# 设置路由
@site.route('/')
def index():
    return render_template('site/index.html')

# 注册
@site.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        new_user = BlogUser(name=form.name.data, password=form.password.data)
        db.session.add(new_user)
        db.session.commit()

        flash("注册成功, 请登录!")
        
        return redirect(url_for('site.login'))
    return render_template('auth/register.html',obj_form=form)

# 登录
@site.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = BlogUser.query.filter_by(name=form.name.data).one()

        login_user(user, remember=form.remember.data)
        identity_changed.send(
            current_app._get_current_object(), identity=Identity(user.id)
        )

        flash("登录成功", category="success")
        return redirect(url_for('blog.article_list', page=1))
    return render_template('auth/login.html',obj_form=form)

# 登出
@site.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    identity_changed.send(
        current_app._get_current_object(), identity=AnonymousIdentity()
    )
    flash("退出登录成功", category="success")
    return redirect(url_for('site.login'))

app/site/__init__.py
from flask import Blueprint

from config import TEMPLATES_DIR, STATIC_DIR

# 创建一个蓝图对象，设置别名，模板文件地址，静态文件地址
site = Blueprint('site', __name__,
    template_folder=TEMPLATES_DIR,
    static_folder=STATIC_DIR)

# 这里导入是为了在解释时，蓝图能加载到views文件中的路由数据
from app.site import views

app/site/views.py
# 获取蓝图
from app.site import site
# 获取数据库模型对象和SQLAlchemy对象db，注意不可使用app模块中的db
# from app.site.models import *

# 设置路由
@site.route('/')
def index():
    return 'site首页'

app/templates/site/base.html
<!DOCTYPE html>
<html class="full-height" lang="zh">

<head class="page-brand">
    <meta charset="UTF-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no, width=device-width" name="viewport">
    <meta name="theme-color" content="#3f51b5">    <title>{% block title %}{% endblock %}</title>
    <!-- css -->
	{% include "site/css.html" %}
    {% block css %}{% endblock %}
    {% macro render_pagination(endpoint, pagination,  tag_id) %}
    <nav>
        <ul class="pagination">
            <li class="page-item">
                {% if pagination.has_prev %}
                <a class="page-link" href="{{ url_for(endpoint, page=pagination.prev().page, tag_id=tag_id) }}"
                    aria-label="Previous">
                    {% else %}
                    <a class="page-link" href="{{ url_for(endpoint, page=1, tag_id=tag_id) }}" aria-label="Previous">
                        {% endif %}
                        <span aria-hidden="true">«</span>
                    </a>
            </li>
            {% for page in pagination.iter_pages() %}
            {% if page %}
            {% if page!=pagination.page %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for(endpoint, page=page, tag_id=tag_id) }}">
                    {{page}}
                </a>
            </li>
            {% else %}
            <li class="page-item active"><a class="page-link" href="">{{page}}</a></li>
            {% endif %}
            {% else %}
            <li class="page-item"><a class="page-link">...</a></li>
            {% endif %}
            {% endfor %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for(endpoint, page=pagination.next().page, tag_id=tag_id) }}"
                    aria-label="Next">
                    <span aria-hidden="true">»</span>
                </a>
            </li>
        </ul>
    </nav>
    {% endmacro %}
</head>

<body class="off-canvas-sidebar" id="top">
    <div class="fakeloader"></div>
    {% block body %}
    {% endblock %}
    
    {% include "site/js.html" %}
    {% block js %}{% endblock %}
</body>

</html>

app/templates/site/css.html
<link href="{{ url_for('static', filename='assets/css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='assets/css/material-dash.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='assets/css/animate.min.css') }}" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="{{ url_for('static', filename='css/mdb.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='css/fakeLoader.css') }}" rel="stylesheet">
<link href="favicon.ico" type="image/x-icon" rel="shortcut icon">

<style>
    @import url("{{ url_for('static', filename='assets/css/font-awesome.min.css') }}");

    @font-face {
        font-family: title-speed;
        src: url("{{ url_for('static', filename='fonts/LobsterTwo-Regular.otf') }}");
    }

    .navbar-brand {
        font-family: title-speed;
        font-size: 1.2rem;
        font-weight: 500;

    }

    body {
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #212529;
        text-align: left;
        background-color: #fff;

    }

    #intro {
        background: url("{{ url_for('static', filename='img/random.jpeg') }}") no-repeat center center;
        background-size: cover;
    }


    #intro .h6 {
        font-weight: 300;
        line-height: 1.7;
    }

    .hm-gradient .full-bg-img {
        background: rgba(42, 27, 161, 0.7);
        background: linear-gradient(45deg, rgba(42, 27, 161, 0.7), rgba(29, 210, 177, 0.7) 100%);
    }

    @media (max-width: 450px) {
        .margins {
            margin-right: 1rem;
            margin-left: 1rem;
        }
    }

    #pricing .lead {
        opacity: 0.7;
    }

    #pricing .card-image {
        background: url("img/login.jpeg") no-repeat center center;
    }

    #pricing ul li {
        font-size: 1.1em;
    }

    .text-white {
        color: #fff !important;
    }

    .row {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-wrap: wrap;
        flex-wrap: wrap;
        margin-right: -15px;
        margin-left: -15px;
    }


    .align-items-center {
        -webkit-box-align: center !important;
        -ms-flex-align: center !important;
        align-items: center !important;
    }

    .d-flex {
        display: -webkit-box !important;
        display: -ms-flexbox !important;
        display: flex !important;
    }


    @media (min-width: 992px) {
        .col-lg-6 {
            -webkit-box-flex: 0;
            -ms-flex: 0 0 50%;
            flex: 0 0 50%;
            max-width: 50%;
        }

        .col-lg-4 {
            -webkit-box-flex: 0;
            -ms-flex: 0 0 33.333333%;
            flex: 0 0 33.333333%;
            max-width: 33.333333%;
        }
    }

    @media (min-width: 1200px) {
        .col-xl-5 {
            -webkit-box-flex: 0;
            -ms-flex: 0 0 41.666667%;
            flex: 0 0 41.666667%;
            max-width: 41.666667%;
        }

        .col-xl-7 {
            -webkit-box-flex: 0;
            -ms-flex: 0 0 58.333333%;
            flex: 0 0 58.333333%;
            max-width: 58.333333%;
        }

        .pr-lg-5,
        .px-lg-5 {
            padding-right: 3rem !important;
        }

    }

    .col-1 {
        -webkit-box-flex: 0;
        -ms-flex: 0 0 8.333333%;
        flex: 0 0 8.333333%;
        max-width: 8.333333%;
        padding-right: 15px;
        padding-left: 15px;
    }

    .col-10 {
        -webkit-box-flex: 0;
        -ms-flex: 0 0 83.333333%;
        flex: 0 0 83.333333%;
        max-width: 83.333333%;
        padding-right: 15px;
        padding-left: 15px;
    }

    .col-md-12 {
        position: relative;
        width: 100%;
        min-height: 1px;
        padding-right: 15px;
        padding-left: 15px;
    }

    }

    .lead {
        font-size: 1.25rem;
        font-weight: 300;
    }

    .h1 {
        font-size: 2.5rem;
    }

    .h1,
    .h2,
    .h3,
    .h4,
    .h5,
    .h6,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        margin-bottom: .5rem;
        font-family: inherit;
        font-weight: 500;
        line-height: 1.2;
        color: inherit;
    }

    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
        margin-top: 0;
        margin-bottom: .5rem;
    }

    .h5,
    h5 {
        font-size: 1.25rem;
    }

    p {
        margin-top: 0;
        margin-bottom: 1rem;
    }

    .card-body {
        -webkit-box-flex: 1;
        -ms-flex: 1 1 auto;
        flex: 1 1 auto;
        padding: 1.25rem;
    }

    sup {
        top: -.5em;
    }

    sub,
    sup {
        position: relative;
        font-size: 75%;
        line-height: 0;
        vertical-align: baseline;
    }

    .rounded {
        border-radius: .25rem !important;
    }

    .img-fluid {
        max-width: 100%;
        height: auto;
    }

    img {
        vertical-align: middle;
        border-style: none;
    }

    .no-gutters {
        margin-right: 0px;
        margin-left: 0px;
    }

    @font-face {
        font-family: anticon;
        src: url("https://at.alicdn.com/t/font_zck90zmlh7hf47vi.eot");
        src: url("https://at.alicdn.com/t/font_zck90zmlh7hf47vi.eot?#iefix") format("embedded-opentype"), url("https://at.alicdn.com/t/font_zck90zmlh7hf47vi.woff") format("woff"), url("https://at.alicdn.com/t/font_zck90zmlh7hf47vi.ttf") format("truetype"), url("https://at.alicdn.com/t/font_zck90zmlh7hf47vi.svg#iconfont") format("svg")
    }

    .anticon-down::before {
        content: "\E61D";
    }

    .anticon::before {
        display: block;
        font-family: anticon !important;
    }

    .anticon {
        display: inline-block;
        font-style: normal;
        vertical-align: baseline;
        text-align: center;
        text-transform: none;
        line-height: 1;
        text-rendering: optimizeLegibility;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }

    .banner0-icon {
        bottom: 20px;
        font-size: 24px;
        position: absolute;
        left: 50%;
        margin-left: -12px;
        color: #fff;
    }

    @-moz-keyframes bounce {

        0%,
        20%,
        50%,
        80%,
        100% {
            -moz-transform: translateY(0);
            transform: translateY(0);
        }

        40% {
            -moz-transform: translateY(-30px);
            transform: translateY(-30px);
        }

        60% {
            -moz-transform: translateY(-15px);
            transform: translateY(-15px);
        }
    }

    @-webkit-keyframes bounce {

        0%,
        20%,
        50%,
        80%,
        100% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
        }

        40% {
            -webkit-transform: translateY(-30px);
            transform: translateY(-30px);
        }

        60% {
            -webkit-transform: translateY(-15px);
            transform: translateY(-15px);
        }
    }

    @keyframes bounce {

        0%,
        20%,
        50%,
        80%,
        100% {
            -moz-transform: translateY(0);
            -ms-transform: translateY(0);
            -webkit-transform: translateY(0);
            transform: translateY(0);
        }

        40% {
            -moz-transform: translateY(-30px);
            -ms-transform: translateY(-30px);
            -webkit-transform: translateY(-30px);
            transform: translateY(-30px);
        }

        60% {
            -moz-transform: translateY(-15px);
            -ms-transform: translateY(-15px);
            -webkit-transform: translateY(-15px);
            transform: translateY(-15px);
        }
    }

    .bounce {
        -moz-animation: bounce 3s infinite;
        -webkit-animation: bounce 3s infinite;
        animation: bounce 3s infinite;
    }
</style>

app/templates/site/footer.html
<footer class="page-footer indigo darken-2 center-on-small-only pt-0 mt-0">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="mb-5 flex-center">
          <a class="px-3"><i class="fa fa-facebook fa-lg white-text"></i></a>
          <a class="px-3"><i class="fa fa-twitter fa-lg white-text"></i></a>
          <a class="px-3"><i class="fa fa-google-plus fa-lg white-text"></i></a>
          <a class="px-3"><i class="fa fa-linkedin fa-lg white-text"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container-fluid">
      <p>
        &copy; <a href="/"></a> @2019
        <a href="/" target="_blank"> Onekki'Site </a>
      </p>
    </div>
  </div>
</footer>

app/templates/site/header.html
<header>
    <nav class="navbar navbar-primary navbar-transparent navbar-absolute">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand  animated swing" href="/">Onekki's Site</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        <a href="/">
                            <i class="material-icons">dashboard</i> 首页
                        </a>
                    </li>
                    <li class="">
                        <a href="{{ url_for('site.register') }}">
                            <i class="material-icons">person_add</i> 注册
                        </a>
                    </li>
                    <li class="">
                        <a href="{{ url_for('site.login') }}">
                            <i class="material-icons">fingerprint</i> 登陆
                        </a>
                    </li>
                    <li class="">
                        <a href="{{ url_for('blog.article_list', page=1)}}">
                            <i class="material-icons">turned_in_not</i> 博客
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <section class="view hm-gradient" id="intro">
        <div class="full-bg-img d-flex align-items-center">
            <div class="container">
                <div class="row no-gutters">
                    <div class="col-md-12 col-lg-12 text-center text-md-left margins">
                        <div class="white-text">
                            <div class="wow fadeInLeft" data-wow-delay="0.3s">
                                <div class="h1" style="font-family: title-speed;">Onekki's Site</div>
                                <h1 class="h5-responsive font-bold mt-sm-5">OUR STORY STARTS HERE.</h1>
                                <div class="h6" style="text-transform:none">
                                    你和我的故事在这里展开.
                                </div>
                            </div><br>
                            <!-- <div class="wow fadeInLeft" data-wow-delay="0.3s"><a
                                    class="btn btn-white dark-grey-text font-bold ml-0" href="auth/register.html"><i
                                        class="fa fa-play mr-1"></i>註冊</a><a
                                    class="btn btn-outline-white waves-effect waves-light" href="auth/login.html">登陸<div
                                        class="ripple-container"></div></a></div>
                            <a class="btn btn-outline-white waves-effect waves-light" href="https://t.me/justssr"
                                target="view_window"> <i class="fa fa-telegram"></i> Telegram公告頻道<div
                                    class="ripple-container"></div></a> -->
                        </div>
                    </div>
                </div>
                <div class="banner0-icon"><i class="anticon anticon-down bounce"></i></div>
            </div>
        </div>
    </section>
</header>

app/templates/site/index.html
{% extends 'site/base.html' %}
{% block body %}
{% include "site/header.html" %}

<div id="content">
    
</div>

{% include "site/footer.html" %}
{% endblock %}

app/templates/site/js.html
<!--  <script src="//cdn.staticfile.org/jquery/2.2.1/jquery.min.js"></script> -->
<script src="{{ url_for('static', filename='js/jquery-2.2.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='assets/js/perfect-scrollbar.jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='assets/js/material-dashboard.js') }}"></script>
<script src="{{ url_for('static', filename='assets/js/material.min.js') }}"></script>
<script src="https://cdn.justssr.com/assets/js/love.js"></script>
<!--  <script text="text/javascript" src="/assets/js/particle.js"></script> -->
<script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/mdb.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/fakeLoader.min.js') }}"></script>

<script>new WOW().init();</script>
<script>
    $(document).ready(function () {
        $(".fakeloader").fakeLoader({
            timeToHide: 2000,
            bgColor: "#3498db",
            spinner: "spinner4"
        });
    });
</script>