app/blog/models.py
# coding: utf-8
from app import db
from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship


class BlogArticle(db.Model):
    __tablename__ = 'blog_article'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(45))
    content = db.Column(db.Text)
    publish_time = db.Column(db.DateTime)
    user_id = db.Column(db.ForeignKey('blog_user.id'), index=True)
    tag_id = db.Column(db.ForeignKey('blog_tag.id'), index=True)

    tag = db.relationship('BlogTag', primaryjoin='BlogArticle.tag_id == BlogTag.id', backref='blog_articles')
    user = db.relationship('BlogUser', primaryjoin='BlogArticle.user_id == BlogUser.id', backref='blog_articles')


class BlogComment(db.Model):
    __tablename__ = 'blog_comment'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    content = db.Column(db.Text)
    time = db.Column(db.DateTime)
    article_id = db.Column(db.ForeignKey('blog_article.id'), index=True)

    article = db.relationship('BlogArticle', primaryjoin='BlogComment.article_id == BlogArticle.id', backref='blog_comments')


class BlogTag(db.Model):
    __tablename__ = 'blog_tag'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    article_id = db.Column(db.ForeignKey('blog_tag.id'), index=True)

    article = db.relationship('BlogTag', remote_side=[id], primaryjoin='BlogTag.article_id == BlogTag.id', backref='blog_tags')


class BlogUser(db.Model):
    __tablename__ = 'blog_user'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    password = db.Column(db.String(255))

app/blog/views.py
# 系统模块
import datetime
from flask import render_template, redirect, jsonify, request, flash, url_for, get_flashed_messages, abort
from sqlalchemy import func
from flask_login import login_user, logout_user, login_required, current_user
from flask_principal import identity_changed, current_app, Identity, AnonymousIdentity, Permission, UserNeed
# 插件
from app.blog import blog
from app.plugin import db, permission_poster, permission_admin
from app.database.models import BlogArticle, BlogComment, BlogRole, BlogTag, BlogUser, t_blog_article_tag, t_blog_user_role
# 导入表单验证
from app.form import ArticleForm, CommentForm, LoginForm, RegisterForm

def json_return(code, msg,data):
    return jsonify({'code':code, 'msg':msg, 'data': data})

def sidebar_data():
    recent_article_list = BlogArticle.query.order_by(
        BlogArticle.publish_time.desc()
    ).limit(5).all()
    count = func.count(t_blog_article_tag.c.article_id).label('total')

    top_tag_list = db.session.query(
        BlogTag.id, BlogTag.name, count
    ).filter(
        BlogTag.id==t_blog_article_tag.c.tag_id
    ).group_by(BlogTag.id).order_by(count.desc()).limit(5).all()

    return recent_article_list, top_tag_list

# 设置路由
@blog.route('/')
def index():
    return render_template('blog/index.html', data = sidebar_data())
# 注册
@blog.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        new_user = BlogUser(name=form.name.data,password=form.password.data)
        db.session.add(new_user)
        db.session.commit()

        flash("注册成功, 请登录!")
        
        return redirect(url_for('blog.login'))
    return render_template('blog/register.html',form=form)

# 登录
@blog.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = BlogUser.query.filter_by(name=form.name.data).one()

        login_user(user, remember=form.remember.data)
        identity_changed.send(
            current_app._get_current_object(), identity=Identity(user.id)
        )

        flash("登录成功", category="success")
        return redirect(url_for('blog.article_list', page=1))
    return render_template('blog/login.html',form=form)
# 登出
@blog.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    identity_changed.send(
        current_app._get_current_object(), identity=AnonymousIdentity()
    )
    flash("退出登录成功", category="success")
    return redirect(url_for('blog.login'))

# 新增文章
@blog.route('/article_add', methods=['GET', 'POST'])
@login_required
def article_add():
    form = ArticleForm()
    if form.validate_on_submit():
        new_article = BlogArticle()
        new_article.title = form.title.data
        new_article.content = form.content.data
        new_article.publish_time = datetime.datetime.now()
        new_article.user = current_user

        db.session.add(new_article)
        db.session.commit()
        return redirect(url_for('blog.article_list', page=1))

    return render_template('blog/article_add.html', form=form)

# 修改文章
@blog.route('/article_update/<int:id>', methods=['GET', 'POST'])
@login_required
@permission_poster.require(http_exception=403)
def article_update(id):
    article = BlogArticle.query.get_or_404(id)

    if not current_user:
        return redirect(url_for('blog.login'))

    if current_user != article.user:
        return redirect(url_for('blog.article', id=id))
    
    permission = Permission(UserNeed(article.user.id))
    if permission.can() or permission_admin.can():
        form = ArticleForm()
        if form.validate_on_submit():
            article.title = form.title.data
            article.content = form.content.data
            article.publish_time = datetime.datetime.now()

            db.session.add(article)
            db.session.commit()
            return redirect(url_for('blog.article', id=article.id))
    else:
        abort(403)
    
    form.title.data = article.title
    form.content.data = article.content
    return render_template('blog/article_update.html', form=form, article=article)

# 获取文章
@blog.route('/article/<int:id>', methods=['GET','POST'])
def article(id):

    form = CommentForm()
    if form.validate_on_submit():
        new_comment = BlogComment()
        new_comment.name=form.name.data
        new_comment.content=form.content.data
        new_comment.time=datetime.datetime.now()
        new_comment.article_id=id
        db.session.add(new_comment)
        db.session.commit()

    article = BlogArticle.query.get_or_404(id)
    tag_list = article.tags
    comment_list = article.comments.order_by(BlogComment.time.desc()).all()
    
    recent_article_list, top_tag_list = sidebar_data()

    return render_template('blog/article.html',
                            article=article,
                            form=form,
                            tag_list=tag_list,
                            comment_list=comment_list,
                            recent_article_list=recent_article_list,
                            top_tag_list=top_tag_list)

@blog.route('/article_list/<int:page>')
def article_list(page):
    filters = []
    tag_id = request.values.get('tag_id')
    if tag_id != None:
        print(tag_id)
        filters.append(t_blog_article_tag.c.tag_id==tag_id)
        filters.append(t_blog_article_tag.c.article_id==BlogArticle.id)
    article_list = BlogArticle.query.filter(*filters).paginate(page, 5)

    recent_article_list, top_tag_list = sidebar_data()
    # return json_return(200, 'success', [i.serialize for i in articles])
    return render_template('blog/article_list.html', 
                            tag_id=tag_id,
                            article_list=article_list, 
                            recent_article_list=recent_article_list,
                            top_tag_list=top_tag_list)

@blog.route('/user_list/<int:page>')
def user_list(page):
    users = BlogUser.query.all()
    # return json_return(200, 'success', [i.serialize for i in articles])
    return render_template('blog/user.html', users=users)

@blog.route('/tag_list/<int:page>')
def tag_list(page):
    tags = BlogTag.query.all()
    # return json_return(200, 'success', [i.serialize for i in articles])
    return render_template('blog/tag.html', tags=tags)

@blog.route('/comment_list/<int:page>')
def comment_list(page):
    comments = BlogComment.query.all()
    # return json_return(200, 'success', [i.serialize for i in articles])
    return render_template('blog/comment.html', comments=comments)

app/controller/api/blog/__init__.py
import datetime
from flask import jsonify, abort
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask_principal import current_app
from flask_restful import Resource, marshal_with
from app.database.models import *
from app.plugins import db

from .blog_parser import *
from .blog_fields import result_fields

# 认证api
class BlogAuthApi(Resource):
    def post(self):
        args = userAuth_post_parser.parse_args()
        user = BlogUser.query.filter_by(name=args['name']).first()
        if user.check_password(args['password']):
            serializer = Serializer(
                current_app.config['SECRET_KEY'],
                expires_in=600
            )
            return {"token": serializer.dumps({"id":user.id}).decode('utf-8')}
        else:
            abort(401)

# 文章api
class BlogArticleApi(Resource):

# 获取文章
    @marshal_with(result_fields)
    def get(self, id=None):
        if id:
            article = BlogArticle.query.filter_by(id=id).first()
            if not article:
                abort(404)
            return {"data": article}
        else:
            args = article_get_parser.parse_args()
            page = args['page'] or 1
            
            if args['user']:
                user = BlogUser.query.filter_by(name=args['user']).first()
                if not user:
                    abort(404)
                article_list = user.articles.order_by(
                    BlogArticle.publish_time.desc()
                ).paginate(page, 10)
            else:
                article_list = BlogArticle.query.order_by(
                    BlogArticle.publish_time.desc()
                ).paginate(page, 10)
            
            return {"data": article_list.items}
    
# 创建文章
    def post(self, id=None):
        if id:
            abort(400)
        else:
            args = article_post_parser.parse_args(strict=True)

            user = BlogUser.verify_auth_token(args['token'])
            if not user:
                abort(401)

            new_article = BlogArticle()
            new_article.title = args['title']
            new_article.content = args['content']
            new_article.publish_time = datetime.datetime.now()
            new_article.user = user

            if args['tags']:
                for item in args['tags']:
                    tag = BlogTag.query.filter_by(name=item).first()
                    if tag:
                        new_article.tags.append(tag)
                    else:
                        new_tag = BlogTag()
                        new_tag.name = item
                        new_article.tags.append(new_tag)
        db.session.add(new_article)
        db.session.commit()
        return (new_article.id, 201)

# 修改文章
    def put(self, id=None):
        if not id:
            abort(400)

        article = BlogArticle.query.filter_by(id=id).first()
        if not article:
            abort(404)

        args = article_put_parser.parse_args()
        user = BlogUser.verify_auth_token(args['token'])

        if not user:
            abort(401)
        if user != article.user:
            abort(403)
    
        if args['title']:
            article.title = args['title']
        if args['content']:
            article.content = args['content']
        if args['tags']:
            for item in args['tags']:
                tag = BlogTag.query.filter_by(name=item).first()
                if tag:
                    article.tags.append(tag)
                else:
                    new_tag = BlogTag()
                    new_tag.name = item
                    article.tags.append(new_tag)
        db.session.add(article)
        db.session.commit()

        return (article.id, 201)

# 删除文章
    def delete(self, id=None):
        if not id:
            abort(400)
        
        article = BlogArticle.query.filter_by(id=id).first()
        if not article:
            abort(401)
        
        args = article_delete_parser.parse_args(strict=True)
        user = BlogUser.verify_auth_token(args['token'])
        if user != article.user:
            abort(403)
        
        db.session.delete(article)
        db.session.commit()

        return "", 204

app/controller/blog/__init__.py
from flask import Blueprint

from config import TEMPLATES_DIR, STATIC_DIR

# 创建一个蓝图对象，设置别名，模板文件地址，静态文件地址
blog = Blueprint('blog', __name__,
    template_folder=TEMPLATES_DIR,
    static_folder=STATIC_DIR)

# 这里导入是为了在解释时，蓝图能加载到views文件中的路由数据
from app.controller.blog import views

app/controller/blog/views.py
# 系统模块
import datetime
from flask import (
    render_template, 
    redirect, 
    jsonify, 
    request, 
    flash, 
    url_for, 
    get_flashed_messages, 
    abort
)
from sqlalchemy import func
from flask_login import (
    login_user, 
    logout_user, 
    login_required, 
    current_user
)
from flask_principal import (
    identity_changed, 
    current_app, 
    Identity,
    AnonymousIdentity, 
    Permission, 
    UserNeed
)
# 插件
from app.controller.blog import blog
from app.plugins import (
    db, 
    permission_poster, 
    permission_admin, 
    cache
)
from app.database.models import *
# 导入表单验证
from app.forms.blog import *

# 侧边栏
@cache.cached(timeout=7200, key_prefix='sidebar_dada')
def sidebar_data():
    recent_article_list = BlogArticle.query.order_by(
        BlogArticle.publish_time.desc()
    ).limit(5).all()
    count = func.count(t_blog_article_tag.c.article_id).label('total')

    top_tag_list = db.session.query(
        BlogTag.id, BlogTag.name, count
    ).filter(
        BlogTag.id==t_blog_article_tag.c.tag_id
    ).group_by(BlogTag.id).order_by(count.desc()).limit(5).all()

    return recent_article_list, top_tag_list

# 设置路由
@blog.route('/')
def index():
    return render_template('blog/index.html', data = sidebar_data())


# 新增文章
@blog.route('/article/add', methods=['GET', 'POST'])
@login_required
def article_add():
    form = ArticleForm()
    if form.validate_on_submit():
        new_article = BlogArticle()
        new_article.title = form.title.data
        new_article.content = form.content.data
        new_article.publish_time = datetime.datetime.now()
        new_article.user = current_user

        db.session.add(new_article)
        db.session.commit()
        return redirect(url_for('blog.article_list', page=1))

    return render_template('blog/article/add.html', obj_form=form)

# 修改文章
@blog.route('/article/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@permission_poster.require(http_exception=403)
def article_edit(id):
    article = BlogArticle.query.get_or_404(id)

    if not current_user:
        return redirect(url_for('site.login'))

    if current_user != article.user:
        return redirect(url_for('blog.article_one', id=id))
    
    permission = Permission(UserNeed(article.user.id))
    if permission.can() or permission_admin.can():
        form = ArticleForm()
        if form.validate_on_submit():
            article.title = form.title.data
            article.content = form.content.data
            article.publish_time = datetime.datetime.now()

            db.session.add(article)
            db.session.commit()
            return redirect(url_for('blog.article_one', id=article.id))
    else:
        abort(403)
    
    form.title.data = article.title
    form.content.data = article.content
    return render_template('blog/article/edit.html', obj_form=form, article_one=article)

# 缓存的key
def make_cache_key(*args, **kwargs):
    path = request.path
    args = str(hash(frozenset(request.args.items())))
    return (path + args).encode('utf-8')

# 获取文章
@blog.route('/article/one/<int:id>', methods=['GET','POST'])
# @cache.cached(timeout=60, key_prefix=make_cache_key)
def article_one(id):

    form = CommentForm()
    if form.validate_on_submit():
        new_comment = BlogComment()
        new_comment.name=form.name.data
        new_comment.content=form.content.data
        new_comment.time=datetime.datetime.now()
        new_comment.article_id=id
        db.session.add(new_comment)
        db.session.commit()

    article = BlogArticle.query.get_or_404(id)
    tag_list = article.tags
    comment_list = article.comments.order_by(BlogComment.time.desc()).all()
    
    recent_article_list, top_tag_list = sidebar_data()

    return render_template('blog/article/one.html',
                            article_one=article,
                            obj_form=form,
                            tag_list=tag_list,
                            comment_list=comment_list,
                            recent_article_list=recent_article_list,
                            top_tag_list=top_tag_list)

# 文章列表
@blog.route('/article/list/<int:page>')
# @cache.cached(timeout=60)
def article_list(page):
    filters = []
    tag_id = request.values.get('tag_id')
    if tag_id != None:
        filters.append(t_blog_article_tag.c.tag_id==tag_id)
        filters.append(t_blog_article_tag.c.article_id==BlogArticle.id)
    article_list = BlogArticle.query.filter(*filters).paginate(page, 8)

    recent_article_list, top_tag_list = sidebar_data()
    # return json_return(200, 'success', [i.serialize for i in articles])
    return render_template('blog/article/list.html', 
                            tag_id=tag_id,
                            article_list=article_list, 
                            recent_article_list=recent_article_list,
                            top_tag_list=top_tag_list)

app/forms/blog/__init__.py
from .blog_article import ArticleForm
from .blog_comment import CommentForm
from .blog_admin import CKTextAreaField

app/templates/blog/article/add.html
{% extends "blog/base.html" %}

{% block title %} New Article {% endblock %}

{% block body %}
    <div class="row">
        <h1 class="text-center">Create A New Article</h1>
        <form method="POST" action="{{ url_for('blog.article_add') }}">
            {{ obj_form.hidden_tag() }}
            <div class="form-group">
                {% if obj_form.title.errors %}
                    {% for e in obj_form.title.errors %}
                        <pa class="help-block">{{ e }}</pa>
                    {% endfor %}
                {% endif %}
                {{ obj_form.title(class_="form-control") }}
            </div>
            <div class="form-group">
                {{ obj_form.content.label }}
                {% if obj_form.content.errors %}
                    {% for e in obj_form.content.errors %}
                        <p class="help-block">{{ e }}</p>
                    {% endfor %}
                {% endif %}
                {{ obj_form.content(class_="form-control", rows="10", cols="80") }}
            </div>
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>
{% endblock %}

app/templates/blog/article/edit.html
{% extends 'blog/base.html' %}

{% block title %} Edit Article {% endblock %}

{% block body %}
    <div class="row">
        <h1 class="text-center">Edit the Article</h1>
        <form method="POST" action="{{ url_for('blog.article_edit', id=article_one.id) }}">
            {{ obj_form.hidden_tag() }}
            <div class="form-group">
                {{ obj_form.title.label }}
                {% if obj_form.title.errors %}
                    {% for e in obj_form.title.errors %}
                        <p class="help-block">{{ e }}</p>
                    {% endfor %}
                {% endif %}
                {{ obj_form.title(class_="form-control", value=article_one.title) }}                
            </div>
            <div class="form-group">
                {{ obj_form.content.label }}
                {% if obj_form.content.errors %}
                    {% for e in obj_form.content.errors %}
                        <p class="help-block">{{ e }}</p>
                    {% endfor %}
                {% endif %}
                {{ obj_form.content(class_="form-control", id="editor", rows="10", cols="80") }}              
            </div>
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
    </div>
{% endblock body %} 

{% block js %}
    <script src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
    <script>
        CKEDITOR.replace('editor');
    </script>
{% endblock %}

app/templates/blog/article/list.html
{% extends "blog/base.html" %}
{% block title %}Onekki Blog{% endblock %}

{% block body_title %}
文章列表
{% endblock %}

{% block body_content %}
<div class="col-xx-12 col-sm-8">
    <!-- 文章列表 -->
    {% for article in article_list.items %}
    <div class="card">
        <div class="card-main">
            <div class="card-inner">
                <p class="card-heading">{{ article.title }}</p>
                <p>{{ article.content|truncate(255)|safe}}</p>
                <a href="{{ url_for('blog.article_one', id=article.id) }}">阅读详情</a>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- end 文章列表 -->
    <!-- 分页 -->
    <div class="card">
        <div class="card-main">
            <div class="card-inner margin-bottom-no margin-top-no">
                <!-- 调用父模版的 macro render_pagination -->
                {{ render_pagination('blog.article_list', article_list, tag_id) }}
            </div>
        </div>
    </div>
</div>

<div class="col-xx-12 col-sm-4">
    <!-- 最近文章 -->
    <div class="card">
        <div class="card-main">
            <div class="card-inner margin-bottom-no">
                <p class="card-heading">最近文章</p>
                <ul>
                    {% for article in recent_article_list %}
                    <li><a href="{{ url_for('blog.article_one', id=article.id) }}">
                            {{ article.title }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <!-- end 最近文章 -->

    <!-- 最热tag -->
    <div class="card">
        <div class="card-main">
            <div class="card-inner">
                <p class="card-heading">热门标签</p>
                <ul>
                    {% for tag in top_tag_list %}
                    <li><a href="{{ url_for('blog.article_list', page=1, tag_id=tag[0]) }}">{{ tag }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <!-- end tag -->
</div>

{% endblock %}

<!-- <div class="content">

    <div class="content-header ui-content-header">
        <div class="container">
            <h1 class="content-heading">文章列表</h1>
        </div>
    </div>

    <div class="container">
        <section class="content-inner">
            <div class="ui-card-wrap">
                

            </div>
        </section>
    </div>

</div> -->

app/templates/blog/article/one.html
{% extends "blog/base.html" %}
{% block title %}Onekki Blog{% endblock %}

{% block body_title %}
Onekki's Blog
{% endblock %}

{% block body_content %}
<div class="card">
    <div class="card-main">
        <div class="card-inner">
            <div class="card-header h3 margin-top-no">
                <p style="text-align: center ;width:100%;"> {{ article_one.title }}</p>
            </div>
            <p class="text-center card-heading h5 margin-no">作者: {{ article_one.user.name }}</p>
            <p class="text-center margin-top-no">{{ article_one.publish_time }}</p>
            <p>{{ article_one.content|safe }}</p>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-main">
        <div class="card-inner">
            <div class="card-header h3 margin-top-no">
                标签
            </div>
            <ul class="padding-left-no">
                {% if tag_list|length > 0 %}
                {% for tag in tag_list %}
                <li><a href="{{ url_for('blog.article_list', page=1, tag_id=tag.id) }}">{{ tag.name }}</a></li>
                {% endfor %}
                {% else %}
                <p class="h4 margin-no">作者没有设置标签.</p>
                {% endif %}

            </ul>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-main">
        <div class="card-inner">
            <div class="card-header h3 margin-top-no">
                评论
            </div>
            <ul class="padding-left-no">
                {% if comment_list|length > 0 %}
                {% for comment in comment_list %}
                <div>
                    name:{{ comment.name }} <br />
                    content:{{ comment.content }}
                </div>
                {% endfor %}
                {% else %}
                <p class="h4 margin-no">文章这么好, 居然还没有人评论.</p>
                {% endif %}
            </ul>
        </div>
    </div>
</div>


<div class="card">
    <div class="card-main">
        <div class="card-inner">
            <div class="card-header h3 margin-top-no">
                发表评论
            </div>
            <form method="POST" action="{{ url_for('blog.article_one', id=article_one.id) }}">
                {{ obj_form.hidden_tag() }}
                <div class="form-group-label margin-top-no">
                    {{ obj_form.name.label(class_="floating-label") }}
                    {% if obj_form.name.errors %}
                    {% for e in obj_form.name.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    {{ obj_form.name(class_="form-control maxwidth-auth") }}
                </div>
                <div class="form-group-label margin-top-no">
                    {{ obj_form.content.label(class_="floating-label") }}
                    {% if obj_form.content.errors %}
                    {% for e in obj_form.content.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    {{ obj_form.content(class_='form-control maxwidth-auth') }}
                </div>
                <div class="text-center">
                    <input class="btn btn-brand maxwidth-auth" type="submit" value="发表评论">
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}